// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart'
    show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGEASfHYQtBPXgZEoYAwZKADQ3Xi-h1VI',
    appId: '1:510718430786:android:efedc519d0c736c50e27db',
    messagingSenderId: '603248941877',
    projectId: 'hypno-book-app',
    storageBucket: 'hypno-book-app.appspot.com',
    authDomain: 'hypno-book-app.firebaseapp.com',
    measurementId: 'G-NLTNJPKT3S',
  );

  static const FirebaseOptions android = FirebaseOptions(
     apiKey: 'AIzaSyDGEASfHYQtBPXgZEoYAwZKADQ3Xi-h1VI',
    appId: '1:510718430786:android:efedc519d0c736c50e27db',
    messagingSenderId: '603248941877',
    projectId: 'hypno-book-app',
    storageBucket: 'hypno-book-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGEASfHYQtBPXgZEoYAwZKADQ3Xi-h1VI',
    appId: '1:510718430786:android:efedc519d0c736c50e27db',
    messagingSenderId: '603248941877',
    projectId: 'hypno-book-app',
    storageBucket: 'hypno-book-app.appspot.com',
    iosClientId: '603248941877-kna3fsu407ta54cqgh0baho11n6dntgb.apps.googleusercontent.com',
    iosBundleId: 'com.skript.hypno',
  );

  static const FirebaseOptions macos = FirebaseOptions(

    apiKey: 'AIzaSyDGEASfHYQtBPXgZEoYAwZKADQ3Xi-h1VI',
    appId: '1:510718430786:android:efedc519d0c736c50e27db',
    messagingSenderId: '603248941877',
    projectId: 'hypno-book-app',
    storageBucket: 'hypno-book-app.appspot.com',
    iosClientId: '603248941877-kna3fsu407ta54cqgh0baho11n6dntgb.apps.googleusercontent.com',
    iosBundleId: 'com.skript.hypno',
  );
}
